parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
#                url: '%env(DATABASE_URL)%'
                # configure these for your database server
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                url: '%env(resolve:DATABASE_URL)%'
            wellness:
                # configure these for your database server
                url: '%env(DATABASE_WELLNESS_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
            cbook:
                # configure these for your database server
                url: '%env(DATABASE_CBOOK_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: '%kernel.debug%'

        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            wellness:
                connection: wellness
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Wellness:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Wellness'
                        prefix: 'App\Entity\Wellness'
                        alias: Wellness
            cbook:
                connection: cbook
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    CBook:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/CBook'
                        prefix: 'App\Entity\CBook'
                        alias: CBook
